"""Update schema

Revision ID: 245fe54affba
Revises: 448a5c41a150
Create Date: 2025-05-05 22:13:50.366831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245fe54affba'
down_revision = '448a5c41a150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    # ### end Alembic commands ###
