"""Update schema

Revision ID: 448a5c41a150
Revises: 6bcdf8904fdd
Create Date: 2025-05-05 10:03:57.494087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448a5c41a150'
down_revision = '6bcdf8904fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
