"""Add mac_address, used_at, expiry to access_codes and index on code

Revision ID: e82a90011659
Revises: dbc7ecba356e
Create Date: 2025-05-07 16:14:56.223478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82a90011659'
down_revision = 'dbc7ecba356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.drop_constraint('access_codes_code_key', type_='unique')
        batch_op.drop_index('idx_access_codes_code')
        batch_op.create_index(batch_op.f('ix_access_codes_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_codes_code'))
        batch_op.create_index('idx_access_codes_code', ['code'], unique=False)
        batch_op.create_unique_constraint('access_codes_code_key', ['code'])

    # ### end Alembic commands ###
